config/routes.rb
Rails.application.routes.draw do
  root 'customers/homes#top' # トップ画面

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers, controllers: {
    sessions:      'customers/sessions', # 会員ログイン画面
    passwords:     'customers/passwords',
    registrations: 'customers/registrations' # 会員登録画面、会員パスワード編集画面
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get 'customers/mypage' => 'customers#mypage' # マイページ画面
    get 'customers/withdraw' => 'customers#withdraw'# 会員退会画面
    patch 'customers/withdraw' => 'customers#withdraw_update'
    get 'customers/fix' => 'customers#fix'
    patch 'customers/fix' => 'customers#fix_update'

  namespace :customers do

    get 'homes/about' => 'homes#about' #アバウト画面

    get 'searches/search' => 'searches#search' # 検索画面

    resources :genres, only: [:show] #ジャンルページ

    post 'contacts/confirm' => 'contacts#confirm'# お問い合わせ確認画面
    get 'contacts/thanks' => 'contacts#thanks'# お問い合わせサンクス画面
    resources :contacts, only: [:index, :create, :new] # お問い合わせ履歴一覧画面、お問い合わせ入力画面

    resources :products, only: [:index, :show] do # 商品一覧画面、商品詳細画面　ジャンル一覧は商品一覧と一緒
      resources :product_comments, only: [:create, :destroy] # 商品のコメント保存、削除
      resource :product_favorites, only:[:create, :destroy] # 商品のお気に入り保存、削除
    end
    resources :product_favorites, only: [:index] # 商品お気に入り一覧画面
    resources :product_comments, only: [:index] # 商品コメント一覧画面

    resources :gyms, only: [:index, :show] do # 施設一覧画面、商品詳細画面　ジャンル一覧は施設一覧と一緒
      resources :gym_comments, only: [:create, :destroy] # 施設のコメント保存、削除
      resource :gym_favorites, only:[:create, :destroy] # 施設のお気に入り保存、削除
    end
    resources :gym_favorites, only: [:index] # 施設お気に入り一覧画面
    resources :gym_comments, only: [:index] # 施設コメント一覧画面
    post 'reservations/confirm' => 'reservations#confirm'# 施設予約確認画面
    get 'reservations/thanks' => 'reservations#thanks'# 施設予約サンクス画面
    resources :reservations, only: [:index, :show, :create, :new]# 施設予約履歴一覧画面、施設予約履歴詳細画面、施設予約保存、施設予約入力画面

  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/contacts_controller.rb
class Customers::ContactsController < ApplicationController

  before_action :authenticate_customer!# ログインしているユーザーのみ入れる
  def index
    @contact = current_customer.contacts #has_many :contactでcustomerとアソシエーションされているため情報を呼び出せる。
  end

  def new
    @contact = Contact.new
  end

  def confirm
    # @contact.customer_id = current_customer.id #customersの情報
    # @contact = Contact.new(contact_params)
    @contact = current_customer.contacts.new(contact_params) #=>省略形
    if @contact.valid? #エラーが無い場合trueを返し，エラーが発生した場合falseを返す
    	render 'confirm'
    else
    	render 'new'
    end
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.customer_id = current_customer.id #customersの情報
    if @contact.save # @contactには１つのレコードが保存
    	 redirect_to  customers_contacts_thanks_path
    else
       flash[:alert] = "お問い合わせが失敗しました"
    	 render 'confirm'
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:contact_name, :contact_email, :contact_content, :contact_status, :task_status)
  end


end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
	def show
		@genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
		@genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

		@products_gyms_all = Product.where(product_valid: true, genre_id: params[:id]) + Gym.where(gym_valid: true, genre_id: params[:id]) # 商品、ジム両方trueの件数・ジャンル絞り・表示カウント
		@genre = Genre.find(params[:id])
		@products = Product.where(genre_id: params[:id]).page(params[:page]).per(3)
		@gyms = Gym.where(genre_id: params[:id]).page(params[:page]).per(3)
	end
end

app/controllers/customers/gym_comments_controller.rb
class Customers::GymCommentsController < ApplicationController

  def index
    @genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
    @genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

    @gym_comments = GymComment.joins(:gym).where(customer_id: current_customer.id, gyms: {gym_valid: true}).order(created_at: :desc).page(params[:page]).per(2) 
    # joinsでGymCommentテーブルとgymテーブルの二つを組み合わせる。
    # whereでGymCommentのcustomer_idとgymsのなかのgym_validを探す。
    # orderでGymCommentのcreated_atを降順で取得。
  end

  def create
    @gym = Gym.find(params[:gym_id])
    @gym_comment = current_customer.gym_comments.new(gym_comment_params)
    @gym_comment.gym_id = @gym.id
    if @gym_comment.save
  	  flash[:notice] = "コメントの投稿が完了しました"
     redirect_to request.referer#成功
    else
      @genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
      @genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に
      @gym = Gym.find(params[:id])
      @gym_comment = GymComment.new #施設へのコメントの為
      @gym_comments = @gym.gym_comments.page(params[:page]).per(2) #コメントのpaginateの為
      flash[:alert] = "コメントの投稿が失敗しました"
     	render 'customers/gyms/show' #失敗
    end
 end

  def destroy
    comment = GymComment.find(params[:id])
    if comment.destroy
      flash[:notice] = "コメントの削除が完了しました"
      redirect_back(fallback_location: root_path) #直前のページに遷移、できなければトップに遷移。
    else
      flash[:alert] = "コメントの削除が失敗しました"
      render 'customers/gyms/show' #失敗
    end
  end

 private
  def gym_comment_params
  	params.require(:gym_comment).permit(:customer_id, :gym_id, :gym_title, :gym_rate, :gym_comment)
  end

end

app/controllers/customers/gym_favorites_controller.rb
class Customers::GymFavoritesController < ApplicationController

	before_action :authenticate_customer!# ログインしているユーザーのみ入れる

  def index
    @genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
    @genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

    @customer = current_customer
    @favorite = @customer.gym_favorites # current_customerのお気に入りを全件取得
    @gyms = Gym.where(gym_valid: true, id: @favorite.pluck(:gym_id)).page(params[:page]).per(1)# 特定のカラムの値を限定して取れる
    @gyms_all = Gym.where(gym_valid: true, id: @favorite.pluck(:gym_id)) # trueの件数＋お気に入りした施設をカウント
  end

	def create
    @gym = Gym.find(params[:gym_id])
    @gym_favorite = GymFavorite.new(gym_id: @gym.id)
    @gym_favorite.customer_id = current_customer.id
    @gym_favorite.save
  end

  def destroy
    @gym = Gym.find(params[:gym_id])
    @gym_favorite = GymFavorite.find_by(gym_id: @gym.id)
    @gym_favorite.customer_id = current_customer.id
    @gym_favorite.destroy

  end
end

app/controllers/customers/gyms_controller.rb
class Customers::GymsController < ApplicationController
	def index
		@genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
		@genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

		@gyms_all = Gym.where(gym_valid: true) # trueの件数表示のみカウント
		@gyms = Gym.where(gym_valid: true).page(params[:page]).per(4) #trueのみ表示＋ページ数指定
	end
	def show
		@genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
		@genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

 		@gym = Gym.find(params[:id])
 		@gym_comment = GymComment.new #施設へのコメントの為
 		@gym_comments = @gym.gym_comments.page(params[:page]).per(2) #コメントのpaginateの為
	end

  private

  def gym_params
  	params.require(:product).permit(:genre_id, :gym_name, :gym_description, :gym_tell, :gym_postal_code, :gym_address, :prefecture_code, :address_city, :address_street, :gym_picture_id, :gym_brand, :gym_valid)
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController

  def top
    @genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
    @genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

    @gyms = Gym.find(GymFavorite.group(:gym_id).order('count(gym_id) desc').limit(4).pluck(:gym_id))
    @products = Product.find(ProductFavorite.group(:product_id).order('count(product_id) desc').limit(4).pluck(:product_id))
    # ProductFavorite.group(:product_id) まず、商品の番号(product_id)が同じものにグループを分ける
    # order('count(product_id) desc' それを、番号の多い順に並び替える
    # limit(3) 表示する最大数を3個に指定する
    # pluck(:product_id)) そして最後に:product_idカラムのみを数字で取り出すように指定。
    # Product.find 最終的に、pluckで取り出される数字を商品のIDとすることでいいね順にproductを取得する事ができる
    # @products = Product.find最後に@productsに代入
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  # super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/product_comments_controller.rb
class Customers::ProductCommentsController < ApplicationController

  def index
    @genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
    @genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

    @product_comments = ProductComment.joins(:product).where(customer_id: current_customer.id, products: {product_valid: true}).order(created_at: :desc).page(params[:page]).per(2) 
    # joinsでGymCommentテーブルとgymテーブルの二つを組み合わせる。
    # whereでGymCommentのcustomer_idとgymsのなかのgym_validを探す。
    # orderでGymCommentのcreated_atを降順で取得。
  end


  def create
    @product = Product.find(params[:product_id])
    @product_comment = current_customer.product_comments.new(product_comment_params)
    @product_comment.product_id = @product.id
    if @product_comment.save
  	  flash[:notice] = "コメントの投稿が完了しました"
      redirect_to request.referer#成功
    else
      @genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
      @genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に
      @product = Product.find(params[:product_id])
      @product_comment = ProductComment.new #商品へのコメントの為
      @product_comments = @product.product_comments.page(params[:page]).per(2) #コメントのpaginateの為
      flash[:alert] = "コメントの投稿が失敗しました"
   	  render 'customers/products/show' #失敗
   end
 end

  def destroy
    comment = ProductComment.find(params[:id])
    if comment.destroy
      flash[:notice] = "コメントの削除が完了しました"
      redirect_back(fallback_location: root_path) #直前のページに遷移、できなければトップに遷移。
    else
      flash[:alert] = "コメントの削除が失敗しました"
      render 'customers/products/show' #失敗
    end
 end

 private
  def product_comment_params
  	params.require(:product_comment).permit(:customer_id, :product_id, :product_title, :product_rate, :product_comment)
  end
end

app/controllers/customers/product_favorites_controller.rb
class Customers::ProductFavoritesController < ApplicationController

  before_action :authenticate_customer!# ログインしているユーザーのみ入れる

  def index
    @genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
    @genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

    @customer = current_customer
    @favorite = @customer.product_favorites # current_customerのお気に入りを全件取得
    @products = Product.where(product_valid: true, id: @favorite.pluck(:product_id)).page(params[:page]).per(1)# pluckは特定のカラムの値を限定して取れる
    @products_all = Product.where(product_valid: true, id: @favorite.pluck(:product_id)) # trueの件数＋お気に入りした商品をカウント
  end

	def create
    @product = Product.find(params[:product_id])
    @product_favorite = ProductFavorite.new(product_id: @product.id)
    @product_favorite.customer_id = current_customer.id
    @product_favorite.save
  end

  def destroy
    @product = Product.find(params[:product_id])
    @product_favorite = ProductFavorite.find_by(product_id: @product.id)
    @product_favorite.customer_id = current_customer.id
    @product_favorite.destroy
  end

end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
	def index
		@genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
		@genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

		@products_all = Product.where(product_valid: true) # trueの件数表示のみカウント
		@products = Product.where(product_valid: true).page(params[:page]).per(4) #trueのみ表示＋ページ数指定
	end

	def show
		@genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
		@genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

 		@product = Product.find(params[:id])
 		@product_comment = ProductComment.new #商品へのコメントの為
 		@product_comments = @product.product_comments.page(params[:page]).per(2) #コメントのpaginateの為
	end

  private

  def product_params
  	params.require(:product).permit(:genre_id, :product_name, :product_description, :product_price, :product_picture_id, :product_brand, :product_valid)
  end

end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
   protected

    def after_update_path_for(resource)
     customers_mypage_path
    end
end

app/controllers/customers/searches_controller.rb
class Customers::SearchesController < ApplicationController

	def search

		@genre_status_products = Genre.where(genre_valid: true, genre_status:1) # render(sidebar)用/true且つgenre_statusが1の時に
		@genre_status_gyms = Genre.where(genre_valid: true, genre_status:0) # render(sidebar)用/true且つgenre_statusが2の時に

		@item_or_club = params[:genre] # application.html.erbで記述した検索フォーム内のgenreが渡される。
    @how_search = params[:direction] # application.html.erbで記述した検索フォーム内のdirectionが渡される。
    if @item_or_club == "item"
      @products = Product.search(params[:search], @item_or_club, @how_search).page(params[:page]).per(1)# モデルにsearchメソッドが定義されており、コントローラーの引数がモデルに渡される。
  	else
  		@gyms = Gym.search(params[:search], @item_or_club, @how_search).page(params[:page]).per(1)
  	end
	end
end

app/views/customers/product_favorites/_product_favorite.html.erb
<% if current_customer %><!--  ログインしているユーザーを指定 -->
  <% if product.product_favorited_by?(current_customer) %>
    <!-- お気に入り登録解除 -->
    <%=link_to customers_product_product_favorites_path(product.id), method: :delete, remote: true do %>
    <!-- アイコン重ねるためspan使用 -->
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x" aria-hidden="true" style="color: #DDDDDD  ;"></i>
      <i class="fa fa-heart fa-stack-1x" aria-hidden="true" style="color: #FF0461;"></i>
    </span>
    <% end %>
  <% else %>
    <!-- お気に入り登録 -->
    <%=link_to customers_product_product_favorites_path(product.id), method: :post, remote: true do %>
    <!-- アイコン重ねるためspan使用 -->
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x" aria-hidden="true" style="color: #DDDDDD  ;"></i>
      <i class="fa fa-heart-o fa-stack-1x" aria-hidden="true" style="color: #333333  ;"></i>
    </span>
    <% end %>
  <% end %>
<% else %>
    <!-- アイコン重ねるためspan使用 -->
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x" aria-hidden="true" style="color: #DDDDDD  ;"></i>
      <i class="fa fa-heart-o fa-stack-1x" aria-hidden="true"></i>
    </span>
<% end %>

app/views/customers/product_favorites/create.js.erb
$("#product_favorite_btn_<%= @product.id %>").html("<%= escape_javascript(render partial: 'customers/product_favorites/product_favorite', locals: { product: @product }) %>")
// @productはproduct_favoritesコントローラーからid取得している。

app/views/customers/product_favorites/destroy.js.erb
$("#product_favorite_btn_<%= @product.id %>").html("<%= escape_javascript(render partial: 'customers/product_favorites/product_favorite', locals: { product: @product }) %>")
// @productはproduct_favoritesコントローラーからid取得している。

app/views/customers/product_favorites/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
      <h1>お気に入り商品一覧</h1>
      <div class="row">
        <div class="productsallcount">
          全<%= @products_all.count %>件
        </div>
        <%= paginate @products %>
      </div>
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3" id="product-index">
            <div class="productimagebox">
              <!-- 画像 -->
              <div class="image-favorite-positon">
              <%= link_to customers_product_path(product.id), data: {"turbolinks" => false}, class: "product-link" do %>
                <%= image_tag product.product_picture_id.thumb.url,  size:"212x212" %>
              <% end %>
              </div>
          <%= link_to customers_product_path(product.id), data: {"turbolinks" => false}, class: "product-link" do %>
            </div>
            <div class="productbox">
              <!-- ブランド -->
              <div class="productbrand-index">
                <%= product.product_brand.truncate(15) %>
              </div>

              <!-- 名前 -->
              <div class="productdescription-index">
                <%= product.product_name.truncate(30) %><br>
              </div>

              <!-- スター平均 -->
              <div class="productstar-index" id="star-rate-<%= product.id %>">
              </div>
              <script>
                //評価星平均
                  // turbolinks:loadはページの切り替えを検知するイベント
                  $(document).on('turbolinks:load', function() {
                    $('#star-rate-<%= product.id %>').raty({
                      size: 36,
                      starOff: "<%= asset_path('star-off.png') %>",
                      starOn: "<%= asset_path('star-on.png') %>",
                      starHalf: "<%= asset_path('star-half.png') %>",
                      half: true,
                      readOnly: true,
                      score: <%= product.product_comments.average(:product_rate).to_f.round(1) %>,
                      //注目ポイント↑ 平均点を算出し、round関数で切り上げ
                    });
                  });
              </script>

              <!-- 平均評価数 -->
              <div class="productaverage-index">
                <% if product.product_comments.average(:product_rate).to_i == 0  %>
                0点
                <% else %>
                <%= product.product_comments.average(:product_rate).round(1) %>点
                <% end %>
              </div>

              <!-- クチコミ合計数 -->
              <div class="reviewcount-index">
                口コミ<%= product.product_comments.count %>件
              </div>

                <!-- 価格 -->
                <div class="productprice-index">
                  価格相場：<%= product.price_with_tax(product.product_price) %>円(税込)
                </div>
          <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="productsallcount">
          全<%= @products_all.count %>件
        </div>
        <%= paginate @products %>
      </div>
    </div>
    <%= render 'layouts/sidebar', products: @genre_status_products, gyms: @genre_status_gyms %><!-- サイドバーcol-md-3 col-lg-3 -->
  </div>
</div>